---
format:
  html:
    code-fold: true
jupyter: python3
---

# Basics of measurement noise modeling {#sec-noisebasics}

Measurement noise is an inherent part of any real-world measurement process, and it can significantly affect the accuracy of localization algorithms.

This chapter explore different types of measurement noise, how to model it. Since the measurement noise represents a complex process that can be influenced by various factors, rather than trying to model it from first principles, a **statistical approach** is often used.

## Statistical model

The most common approach is to use a Gaussian (normal) distribution to model measurement noise, which is characterized by its mean and variance.

The following code simulates measurement noise using a Gaussian distribution and visualizes it. The first step is to generate a large number of noise samples from a Gaussian distribution with a specified mean and standard deviation.

```{python}
import numpy as np
import matplotlib.pyplot as plt
# Simulate measurement noise
np.random.seed(0)  # For reproducibility
num_measurements = 10000

# Simulate noise as a Gaussian distribution
mean_noise = 0
std_dev_noise = 1

# Generate noise samples (i.e. w) using a Gaussian distribution
w_gaussian = np.random.normal(mean_noise, std_dev_noise, num_measurements)

plt.plot(w_gaussian, marker='.', color='g', linestyle='None')
plt.title('Gaussian Measurement Noise Samples')
plt.xlabel('Epoch')
_ = plt.ylabel('Noise value')
```

Then, we can plot the corresponding histogram (by counting the number of samples that fall in each bin) to visualize the distribution of the noise.:

```{python}
plt.hist(w_gaussian, bins=30, density=True, alpha=0.6, color='g')
plt.title('Gaussian Measurement Noise Distribution')
plt.xlabel('Noise Value')
_ = plt.ylabel('Density')
```

The Gaussian distribution is often chosen because of the Central Limit Theorem, which states that the sum of a large number of independent random variables tends to be normally distributed, regardless of the original distribution of the variables.

For comparison, we can also simulate noise using a uniform distribution:

```{python}
# Simulate noise as a Uniform distribution
low_noise = -2
high_noise = 2
w_uniform = np.random.uniform(low_noise, high_noise, num_measurements)
plt.plot(w_uniform, marker='.', color='b', linestyle='None')
plt.title('Uniform Measurement Noise Samples')
plt.xlabel('Epoch')
_ = plt.ylabel('Noise value')
```
```{python}
plt.hist(w_uniform, bins=30, density=True, alpha=0.6, color='b')
plt.title('Uniform Measurement Noise Distribution')
plt.xlabel('Noise Value')
_ = plt.ylabel('Density')
```

In the uniform case, the noise values are equally likely to fall anywhere within the specified range, resulting in a flat distribution. In contrast, the Gaussian distribution has a bell-shaped curve, with most noise values clustered around the mean and fewer values occurring as you move away from the mean.

## Noisy measurements

It is often stated that the noise is **additive** and **independent** of the true signal, which means that the noise is added to the true measurement and does not depend on the value of the true measurement. This assumption simplifies the analysis and allows us to use statistical methods to estimate the true signal from noisy measurements.

Let's consider a simple example of a distance measurement (e.g., range) of a rover and a single node. The following plot shows the true distance to the target (in red) and the noisy measurements (in green) affected by Gaussian noise:

```{python}
# Simulate true distance
x, y = np.linspace(0, 10, num_measurements), np.linspace(0, 10, num_measurements)
x_1, y_1 = 5, 0  # Position of the reference node

# Distance to the target (true signal)
d = np.sqrt((x - x_1)**2 + (y - y_1)**2)

fig, axes = plt.subplots(2, 1)
axes[0].plot(x, y, marker=',', color='r', linestyle='None', label='Rover trajectory')
axes[0].plot(x_1, y_1, marker='o', color='black', linestyle='None', label='Reference Node')
axes[0].legend()
axes[0].set_title('Rover and Reference Node Positions')
axes[0].set_xlabel('X')
_ = axes[0].set_ylabel('Y')

axes[1].plot(d + w_gaussian, marker='.', color='g', linestyle='None', label='Noisy Measurement')
axes[1].plot(d, marker='.', color='r', linestyle='None', label='True Distance')
axes[1].legend()
axes[1].set_title('Distance to the Target')
axes[1].set_xlabel('Epoch')
_ = axes[1].set_ylabel('Distance')

plt.tight_layout()
```

In this plot, the red points represent the true distance to the target, while the green points represent the noisy measurements affected by Gaussian noise. The noise causes the measurements to deviate from the true distance, which will ultimately impact the accuracy that can be achieved by the positioning system.
